# Publish NuGet package for Cross.Pipelines.

trigger:
  branches:
   include:
   - master
  paths:
    include:
    - Core/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Core/*.sln'
  projects: '**/Core/src/*.csproj'
  testProjects: '**/Core/test/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 0
  minor: $[counter(variables['major'], 0)]
  patch: $[counter(variables['minor'], 0)]

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install latest version of NuGet Tools'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'Restore nuget packages for the solution'

- task: DotNetCoreCLI@2
  inputs:
     command: build
     projects: $(projects)
     arguments: '--configuration $(buildConfiguration) /p:Version=>$(major).$(minor).$(patch)-beta /p:AssemblyVersion=>$(major).$(minor).$(patch).$(Build.BuildId)-beta /p:FileVersion=>$(major).$(minor).$(patch).$(Build.BuildId)-beta'
  displayName: 'Build the solution'

- task: DotNetCoreCLI@2
  inputs:
     command: test
     projects: $(testProjects)
     arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  displayName: 'Run the automated tests'

- task: DotNetCoreCLI@2
  inputs:
     command: publish
     publishWebProjects: False
     arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/dll'
     zipAfterPublish: True 
  displayName: 'Publish the dlls to the $(ArtifactStagingDirectory)/dll'

# Push a project
#- task: NuGetCommand@2
#  inputs:
#    packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'
#    command: 'push'
#    configuration: $(buildConfiguration)
#    allowPackageConflicts: true
#    nuGetFeedType: 'internal'
#    publishVstsFeed: 'ea2302d5-a8d1-481c-a7f8-40b10b1d7556/7408c788-39c6-442b-8fad-e72439da7221'
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#  displayName: 'Publish the nuget package to Cross.Pipelines'