name: MyTrout.Pipelines.Hosting

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-pipelines-hosting.yaml'
      - '**/Pipelines/Hosting/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  pull_request:
    paths:
      - '.github/workflows/build-pipelines-hosting.yaml'
      - '**/Pipelines/Hosting/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  workflow_dispatch:
      
jobs:
  build:
    uses: './.github/workflows/template-build-pipelines.yaml'
    with:
      sonar-project-name: 'Pipelines.Hosting'
      working-directory: '/Hosting'
      solution-name: 'MyTrout.Pipelines.Hosting.sln'
      project-version: '4.1.0'
    secrets: inherit
