name: MyTrout.Pipelines.Steps.Serialization.Json

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-pipelines-steps-serialization-json.yaml'
      - 'Steps/Serialization/Json/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  pull_request:
    paths:
      - '.github/workflows/build-pipelines-steps-serialization-json.yaml'
      - 'Steps/Serialization/Json/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/template-build-pipelines.yaml'
    with:
      sonar-project-name: 'Pipelines.Steps.Serialization.Json'
      working-directory: '/Steps/Serialization/Json'
      solution-name: 'MyTrout.Pipelines.Steps.Serialization.Json.sln'
      project-version: '1.2.0'
    secrets: inherit
