name: MyTrout.Pipelines.Steps.Cryptography

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-pipelines-steps-cryptography.yaml'
      - '**/Pipelines/Steps/Cryptography/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  pull_request:
    paths:
      - '.github/workflows/build-pipelines-steps-cryptography.yaml'
      - '**/Pipelines/Steps/Cryptography/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/template-build-pipelines.yaml'
    with:
      sonar-project-name: 'Pipelines.Steps.Cryptography'
      working-directory: '/Steps/Cryptography'
      solution-name: 'MyTrout.Pipelines.Steps.Cryptography.sln'
      project-version: '4.1.1'
    secrets: inherit
