name: MyTrout.Pipelines.Steps.IO.Directories

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-pipelines-steps-io-directories.yaml'
      - '**/Pipelines/Steps/IO/Directories/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  pull_request:
    paths:
      - '.github/workflows/build-pipelines-steps-io-directories.yaml'
      - '**/Pipelines/Steps/IO/Directories/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/template-build-pipelines.yaml'
    with:
      sonar-project-name: 'Pipelines.Steps.IO.Directories'
      working-directory: '/Steps/IO/Directories'
      solution-name: 'MyTrout.Pipelines.Steps.IO.Directories.sln'
      project-version: '1.1.0'
    secrets: inherit
