name: MyTrout.Pipelines.Steps.IO.Compression

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-pipelines-steps-io-compression.yaml'
      - '**/Pipelines/Steps/IO/Compression/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  pull_request:
    paths:
      - '.github/workflows/build-pipelines-steps-io-compression.yaml'
      - '**/Pipelines/Steps/IO/Compression/**/*.*'
      - '!**/*.md'
      - '!**/*.json'
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/template-build-pipelines.yaml'
    with:
      sonar-project-name: 'Pipelines.Steps.IO.Compression'
      working-directory: '/Steps/IO/Compression'
      solution-name: 'MyTrout.Pipelines.Steps.IO.Compression.sln'
      project-version: '6.1.0'
    secrets: inherit
